name: Relatório Semanal

on:
  schedule:
    - cron: "0 12 * * 0"

  workflow_dispatch:

jobs:
  validar:
    runs-on: self-hosted

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Rodar testes automatizados
        uses: cypress-io/github-action@v6

        env:
          CYPRESS_CPF_ASSOCIADO: ${{ secrets.cpf_associado }}
          CYPRESS_SENHA_ASSOCIADO: ${{ secrets.senha_associado }}

        with:
          browser: chrome
          headed: true
          wait-on: ""
          spec: |
            cypress/e2e/TESTES_HOMEPAGE/**/*.cy.js,
            cypress/e2e/TESTES_PORTAL_AREA_NAO_LOGADA/**/*.cy.js,
            cypress/e2e/TESTES_PERFIL_ASSOCIADO/**/*.cy.js